const HOME_IMAGES = {
  banner1: require("./banner1.png"),
  header_bgr: require("./header_bgr.png"),
  heart: require("./heart.png"),
  ic_hoidap: require("./ic_hoidap.png"),
  ic_ketqua: require("./ic_ketqua.png"),
  ic_khamlai: require("./ic_khamlai.png"),
  ic_kienthuc: require("./ic_kienthuc.png"),
  ic_nhathuoc: require("./ic_nhathuoc.png"),
  ic_tuvan: require("./ic_tuvan.png"),
  new_1: require("./new_1.png"),
  new_2: require("./new_2.png"),
  new_3: require("./new_3.png"),
  package_1: require("./package_1.png"),
  package_2: require("./package_2.png"),
  textsdocter: require("./textsdocter.png"),
  search_normal: require("./search-normal.png"),
  call_reminder: require("./call_reminder.png"),
}
export default HOME_IMAGES
