export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const WATCH_SAVE_USER_DATA = 'WATCH_SAVE_USER_DATA';
export const WATCH_UPDATE_USER_DATA = 'WATCH_UPDATE_USER_DATA';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
export const UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION';
export const WATCH_CURRENT_LOCATION = 'WATCH_CURRENT_LOCATION';
